#!/usr/bin/env bash
# install ufw firewall & set requirements

# update
sudo apt-get update

# install UFW if not already installed
sudo apt-get install ufw

# enable UFW
sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp #SSH
sudo ufw allow 443/tcp #HTTPS SSL
sudo ufw allow 80/tcp #HTTP

sudo ufw status
